# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntentCli < Formula
  desc "IntentRegistry CLI — publish and install AI Intents"
  homepage "https://intentregistry.com"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.2.8/intent-darwin-amd64.tar.gz"
      sha256 "6f44583c8eb18b9b3cf6c3a67df22cb4220bdaf25fd39e6d49bdec460b9d2f3a"

      def install
        bin.install "intent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.2.8/intent-darwin-arm64.tar.gz"
      sha256 "fd9024898fd4c91e644966ac5381921c8924ad3b09aa9e87305c5d143fee08f9"

      def install
        bin.install "intent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.2.8/intent-linux-amd64.tar.gz"
      sha256 "80f2d0697333e67617aca7c3e5c1944c044f520ed719981da362db779dbf7e74"
      def install
        bin.install "intent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.2.8/intent-linux-arm64.tar.gz"
      sha256 "6a64e5566f24366a4a2ae28dd5af47120726c56b4053355774a353fee8285e6e"
      def install
        bin.install "intent"
      end
    end
  end

  test do
    system "#{bin}/intent", "--version"
  end
end
