# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IntentCli < Formula
  desc "IntentRegistry CLI — publish and install AI Intents"
  homepage "https://intentregistry.com"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.3.8/intent-darwin-amd64.tar.gz"
      sha256 "5875decfd881ac726821c36d861ff8299099ec911b98a132b23dcbb5526d7fb0"

      def install
        bin.install "intent"
        generate_completions_from_executable(bin/"intent", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.3.8/intent-darwin-arm64.tar.gz"
      sha256 "3d0afdf760791769cecf29aa015203a8da8e59d3f7b8030e8a95029320f594df"

      def install
        bin.install "intent"
        generate_completions_from_executable(bin/"intent", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.3.8/intent-linux-amd64.tar.gz"
      sha256 "6ece86da0f55ce47d78b75cb892393c54c32615503b40b1ef30b7eee17f9c375"
      def install
        bin.install "intent"
        generate_completions_from_executable(bin/"intent", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intentregistry/intent-cli/releases/download/v0.3.8/intent-linux-arm64.tar.gz"
      sha256 "4a69fb1150e31bf7eb246addd4b9a99108065f67818fc1fb23e8537b3cfb6cf4"
      def install
        bin.install "intent"
        generate_completions_from_executable(bin/"intent", "completion")
      end
    end
  end

  test do
    system "#{bin}/intent", "--version"
  end
end
